services:
  backend:
    build:
      context: ./nzeroesg-api
      dockerfile: Dockerfile
    container_name: nzeroesg-backend
    ports:
      - "8000:8000"
    env_file:
      - ./nzeroesg-api/.env
    restart: always

  frontend:
    build:
      context: ./nzeroesg-client
      dockerfile: Dockerfile
    container_name: nzeroesg-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./nzeroesg-client/.env.local
    restart: always
    depends_on:
      - backend
