name: CI/CD Pipeline (NZeroESG)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-backend:
    name: Deploy Backend (FastAPI)
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST "https://api.render.com/deploy/srv-d14ot7gdl3ps738gd9pg?key=MrBvopCi3X8?key=${{ secrets.RENDER_API_KEY }}"

  deploy-frontend:
    name: Deploy Frontend (Next.js)
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST "https://api.render.com/deploy/srv-d14pgqumcj7s73feghf0?key=285fqqE0lzI?key=${{ secrets.RENDER_API_KEY }}"
